module-template: ! 'module MODULE_NAME where

'
extensions:
  GADTs: true
  RankNTypes: true
environment: ghc-7.4.2-stable-13.09
cabal-file: project.cabal
hidden-packages: ''
version: 1
extra-packages: ''
ghc-args:
- -Wall
- -fno-warn-name-shadowing
- -fno-warn-unused-matches
- -fno-warn-unused-binds
excluded-modules: []
